### ISSUE TITLE
Question: canvas or srcset?

### ISSUE THREAD

**Issue by pmeinhardt** [dev-rsilver/plugin-react-static-images#2]
Hey, I was looking for a way of automatically optimizing images for a react-static site, esp. for devices with different screen resolutions. This package looks pretty neat! 💚 

I was glancing through the source code a bit and was just wondering what the motivation was to resize images using a canvas? 🙂 

My initial thought was, it'd be great to define a list of transforms (esp. for different image sizes) and to render all of these sizes out in a build – as physical files. The `<img>`s could then have a proper `srcset` attribute (or use a `<picture>` element) and user agents would only need to download the resolution they're interested in – saving some bandwidth and device memory. 🤔 (for reference [MDN: Responsive Images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images))

I might be missing something though and probably there were good reasons to implement it like this. I just couldn't find any documentation about this.

Thanks 👋 🙂

**Comment by dev-rsilver** [comment]
@pmeinhardt Thanks for the nice comments!

The plugin has three primary points of entry:

1. Server-side code located in src/components/nodeImage.js, which is where the functionality for Images.get() is located
2. Client-side code located in src/browser.api.js which implements a React Static browser plugin
3. The ImageComponent located in src/components/image.js

Images.get() should be called when setting up routes in React Static and will produce actual images (files).

The browser plugin in browser.api.js maintains a map of the ImageComponents being utilized in a page so that they can, for instance, be lazy-loaded via an IntersectionObserver if necessary.

When you use an ImageComponent in a page, the image will be populated from the information you pass to it from the route data. The image may be base64 encoded and passed through the route data depending on settings or point to an image's url.

The "responsive" feature generates a series of images at build time and then lets the browser (client-side, via JS) selectively choose the best image to display.

One of my goals for the plugin was to make ImageComponent a replacement for the img element with respect to CSS styling. I encountered a number of issues related to this goal with respect to image placeholders, and my solution was to resize, or generate blank (white), placeholders on the fly. The canvas you're seeing in image.js is about resizing or creating placeholder images, not about resizing the final images.

**Comment by dev-rsilver** [comment]
Depending on the value of maxAssetSize, Images.get() may return base64 encoded data instead of resulting in files being created.

**Comment by pmeinhardt** [comment]
Ah 💡  I see now. Thank you so much for taking the time to clarify 💚 

So the canvases are used for generating placeholder images that have the same size as the image to be loaded (even though the temporary placeholder is generated from a very low-res version of the image that has much lower width+height to begin with). So this is how you make sure that the element behaves/layouts correctly in the browser as explained here:

https://github.com/dev-rsilver/plugin-react-static-images/blob/e4c9701fbf2c1bfda5a746eae36b3da40be76965/src/components/image.js#L220-L224

Neat 👍

**Comment by pmeinhardt** [comment]
One follow-up question: Would it then be possible (and maybe a good idea) to generate the placeholder images with the correct sizes at build time (similar to the responsive images) and getting rid of resizing in the browser? 🤔

**Comment by dev-rsilver** [comment]
Are you experiencing issues with the client-side resizing? If you're trying to modify the plugin, your idea should be possible. A few things you might consider:

- Build time would likely increase. With the responsive image feature, for instance, you would need a placeholder for each of the responsive images generated.

- You might want to take a look at the size of a pre-sized placeholder vs the current small placeholder that's then resized client-side.

- When Images.get() is called, each image is either represented via base64 encoded data or a url. Each pre-sized placeholder will be similar in terms of how it appears, but the placeholders will all be different images. The placeholders are likely to be returned as base64 encoded data, depending on settings, which means they'll then be passed into the route data instead of being stored as files... That means potentially passing a lot of extra data to the route.

Let me know what you think!

**Comment by pmeinhardt** [comment]
Hey, just to clarify: I didn't experience any issues with the client-side resizing 🙂 

My thought was simply that creating the different sizes at build-time could have a few advantages which _might_ make it a worthwhile change to this package (despite increased build-time), i.e.

- Resizing happens once, on the build host, instead of once for every page view/for every user-agent
- This might be more resource-efficient (computation/battery/…), esp. for low-end devices
- The client-side JS could be simplified
- It might be possible to use the code that generates the responsive images to generate the different placeholder sizes in the same manner
- It might be easier to generate highly optimized images while building than it is on the client

But it's just a thought ✌️

**Comment by dev-rsilver** [comment]
Although I decided to implement the plugin using client-side resizing based, in part, on the information I provided above, I decided to spend some time re-evaluating the implementation after reading your response.

I observed the ImageComponent using the profiler in the browser, looked at the time it takes to transfer images with network throttling enabled, and compared the size of small placeholder images vs pre-sized placeholder images.

In general, the pre-sized placeholders, even if reducing the quality of the JPEGs significantly, tended to be many multiples larger than their non-pre-sized counterparts. Additionally, as I mentioned before, it would probably be necessary to transfer multiple pre-sized images if the responsive images are enabled because the appropriately sized images are being selected client-side.

I do agree that there is a non-zero performance cost to the canvas-based resizing operation, but I think it's a reasonable trade-off given the network transfer reduction.

I guess it depends on whether one thinks it's more important to optimize for processor speed or network transfer. My personal opinion is that it's better to optimize for network transfer, so I think it makes sense to leave things as they are currently implemented.

**Comment by pmeinhardt** [comment]
Nice! 🤘 Thanks a lot for taking the time to even re-evaluate your design decisions. This is really awesome.

Makes sense, the way you describe it. It seems like a pretty good trade-off indeed to only transfer one really small image for generating placeholders of different sizes dynamically and reducing the overall network transfer. 💚 

Sounds like this discussion would neatly fit into the README to document your design decisions 🙂  (or you could at least link to your comments & explanations here in the issue as a quick alternative).

Thanks again! Cheers 👋
